name: Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        timeout-minutes: 5
        run: |
          python -m pip install --upgrade pip --no-cache-dir
          pip install --no-cache-dir flake8 pytest
      
      - name: Lint with flake8
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      
      - name: Run script.py
        run: python script.py
      
      - name: Run tests with pytest
        run: pytest test_eg.py > test-result-${{ matrix.os }}-${{ matrix.python-version }}.log 2>&1 || echo "Tests failed but continuing"
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.python-version }}
          path: test-result-${{ matrix.os }}-${{ matrix.python-version }}.log
